function out = chainStruct(varargin)

if nargin == 0
    out = struct(...
        'fieldsUse',[],...
        'props_crys',[],...
        'props_len',[],...
        'props_theta',[],...
        'props_mixType',[],...
        'props_lams',[],...
        'props_spotRad',[],...
        'props_taus',[],...
        'props_energies',[],...
        'props_specPhases',[]...
        );
    return
elseif nargin == 7
    out = struct(...
        'fieldsUse',varargin{1},...
        'props_crys',varargin{1},...
        'props_len',varargin{1},...
        'props_theta',varargin{1},...
        'props_mixType',varargin{1},...
        'props_lams',varargin{1},...
        'props_spotRad',varargin{1},...
        'props_taus',[],...
        'props_energies',[],...
        'props_specPhases',[]...
        );
elseif nargin == 10
    out = struct(...
        'fieldsUse',varargin{1},...
        'props_crys',varargin{2},...
        'props_len',varargin{3},...
        'props_theta',varargin{4},...
        'props_mixType',varargin{5},...
        'props_lams',varargin{6},...
        'props_spotRad',varargin{7},...
        'props_taus',varargin{8},...
        'props_energies',varargin{9},...
        'props_specPhases',varargin{10}...
        );
else
    error('Improper number of inputs')
end

end