function genField(this)

nFields = length(this.props_lams);

% Indexing: field (t or w), zStep (1-nZSteps), lambda (pump, signal, idler), points (:).
this.eField = complex( zeros(...
    2,this.grid_nZSteps+1,nFields,this.grid_nPts...
    ) );
this.eField(1) = 0 + eps(0)*1i;



for ii = 1:nFields
    
    if isempty(this.chain_Fields) || max(this.chain_Fields(:,1,ii,:),[],'all') == 0
        
        if ii ~= nFields
            
            this.eField(1,1,ii,:) = this.fieldPK(...
                this.props_energies(ii),...
                this.props_spotRad,...
                this.props_taus(ii),...
                this.eqns_Index{ii}(this.props_lams(ii)) )...
                .* exp( - (1/2) .* this.const_fwhm .*...
                ( (this.list_t + 0) ./ this.props_taus(ii) ).^2 );
            
        elseif ii == nFields
            
            this.eField(1,1,ii,:) = this.fieldPK(...
                this.props_energies(ii),...
                this.props_spotRad,...
                this.props_taus(ii),...
                this.eqns_Index{ii}(this.props_lams(ii),this.props_theta) )...
                .* exp( - (1/2) .* this.const_fwhm .*...
                ( (this.list_t + 0) ./ this.props_taus(ii) ).^2 );
            
        end
        
        this.eField(2,1,ii,:) = this.fft(this.eField(1,1,ii,:));
    else
        
        this.eField(:,1,ii,:) = this.chain_Fields(:,1,ii,:);
        
    end
    
    this.eField(2,1,ii,:) = this.eField(2,1,ii,:) .*...
        permute(...
        exp( 1i .* this.eqns_phase(...
        this.list_lambda(ii,:),...
        this.props_lams(ii),...
        this.props_specPhases(ii,1),...
        this.props_specPhases(ii,2),...
        this.props_specPhases(ii,3),...
        this.props_specPhases(ii,4)...
        ) ),...
        [4,3,1,2]) ;
    
    this.eField(1,1,ii,:) = this.ifft(this.eField(2,1,ii,:));
    
    
    
end





end